<form method="post" action="game/">
<form method="POST">
    <h2>Choose count of players</h2>

    <select name="countOfPlayers">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>	  
    </select>

    <input type="submit" value="Go" name="go">

</form>
